/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as wizardSelectCategoryRouteImport } from './routes/(wizard)/select-category'
import { Route as authSelectStaffRouteImport } from './routes/(auth)/select-staff'
import { Route as authNewDeviceRouteImport } from './routes/(auth)/new-device'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const wizardSelectCategoryRoute = wizardSelectCategoryRouteImport.update({
  id: '/(wizard)/select-category',
  path: '/select-category',
  getParentRoute: () => rootRouteImport,
} as any)
const authSelectStaffRoute = authSelectStaffRouteImport.update({
  id: '/(auth)/select-staff',
  path: '/select-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const authNewDeviceRoute = authNewDeviceRouteImport.update({
  id: '/(auth)/new-device',
  path: '/new-device',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-device': typeof authNewDeviceRoute
  '/select-staff': typeof authSelectStaffRoute
  '/select-category': typeof wizardSelectCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-device': typeof authNewDeviceRoute
  '/select-staff': typeof authSelectStaffRoute
  '/select-category': typeof wizardSelectCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/new-device': typeof authNewDeviceRoute
  '/(auth)/select-staff': typeof authSelectStaffRoute
  '/(wizard)/select-category': typeof wizardSelectCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-device' | '/select-staff' | '/select-category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-device' | '/select-staff' | '/select-category'
  id:
    | '__root__'
    | '/'
    | '/(auth)/new-device'
    | '/(auth)/select-staff'
    | '/(wizard)/select-category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authNewDeviceRoute: typeof authNewDeviceRoute
  authSelectStaffRoute: typeof authSelectStaffRoute
  wizardSelectCategoryRoute: typeof wizardSelectCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(wizard)/select-category': {
      id: '/(wizard)/select-category'
      path: '/select-category'
      fullPath: '/select-category'
      preLoaderRoute: typeof wizardSelectCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/select-staff': {
      id: '/(auth)/select-staff'
      path: '/select-staff'
      fullPath: '/select-staff'
      preLoaderRoute: typeof authSelectStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/new-device': {
      id: '/(auth)/new-device'
      path: '/new-device'
      fullPath: '/new-device'
      preLoaderRoute: typeof authNewDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authNewDeviceRoute: authNewDeviceRoute,
  authSelectStaffRoute: authSelectStaffRoute,
  wizardSelectCategoryRoute: wizardSelectCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
