import type { CategoryMeta } from "./types"

export const CATEGORIES: CategoryMeta[] = [
  {
    id: "smartphone",
    label: "Smartphone",
    description: "Mobile phones & accessories",
    modelCount: 142,
    avgRepairTime: "45 min",
    dailyIntakes: 23,
    tag: "Most Popular",
    iconBg: "bg-primary/15",
    iconText: "text-primary",
    popularBrands: ["Apple", "Samsung", "Xiaomi", "Oppo"],
    priceFrom: 80,
  },
  {
    id: "laptop",
    label: "Laptop",
    description: "Notebooks & ultrabooks",
    modelCount: 89,
    avgRepairTime: "1 hr 20 min",
    dailyIntakes: 8,
    tag: null,
    iconBg: "bg-secondary/15",
    iconText: "text-secondary",
    popularBrands: ["Apple", "Dell", "HP", "Lenovo"],
    priceFrom: 150,
  },
  {
    id: "tablet",
    label: "Tablet",
    description: "iPads & Android tablets",
    modelCount: 56,
    avgRepairTime: "55 min",
    dailyIntakes: 5,
    tag: "Trending",
    iconBg: "bg-accent/15",
    iconText: "text-accent-foreground",
    popularBrands: ["Apple", "Samsung", "Huawei", "Xiaomi"],
    priceFrom: 120,
  },
  {
    id: "wearable",
    label: "Wearable",
    description: "Smartwatches & fitness bands",
    modelCount: 34,
    avgRepairTime: "30 min",
    dailyIntakes: 3,
    tag: null,
    iconBg: "bg-chart-5/15",
    iconText: "text-chart-5",
    popularBrands: ["Apple", "Samsung", "Garmin", "Huawei"],
    priceFrom: 60,
  },
  {
    id: "console",
    label: "Console",
    description: "Gaming consoles & controllers",
    modelCount: 21,
    avgRepairTime: "2 hr",
    dailyIntakes: 2,
    tag: "Last used",
    iconBg: "bg-destructive/10",
    iconText: "text-destructive",
    popularBrands: ["Sony", "Nintendo", "Microsoft", "Steam"],
    priceFrom: 100,
  },
  {
    id: "other",
    label: "Other",
    description: "Miscellaneous electronics",
    modelCount: 12,
    avgRepairTime: "Varies",
    dailyIntakes: 1,
    tag: null,
    iconBg: "bg-fuchsia-500/10",
    iconText: "text-muted-foreground",
    popularBrands: ["DJI", "Bose", "Sony", "Canon"],
    priceFrom: 50,
  },
]
