### Get user list
GET http://localhost:9900/users
Accept: application/json

### Register
POST http://localhost:9900/users
Content-Type: application/json
Accept: application/json

{
  "password": "secure123",
  "yay": "asikdjl"
}